title: Copied Kavithai - Kavithai Database
description: Kavithai Storage Blog - Copied Kavithai From Tamil Kavithai Sites, Facebook Profiles, and Twitter Profiles - Tamil Kavithai and Tamil Quotes Status.
author:
  name: Tamil SMS,
  email: me@santhoshveer.com,
  url: https://copied.kavithai.site/about/