title: Copied Kavithai - Kavithai Database - தமிழ் கவிதை Site
description: தமிழ் கவிதை Site - Copied Kavithai From Tamil Kavithai Sites, Facebook Profiles, and Twitter Profiles - Tamil Kavithai and Tamil Quotes Status and Stories.
author:
  name: Tamil SMS,
  email: me@santhoshveer.com,
  url: https://copied.kavithai.site/about/